#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
============================================================================
PLANETVORTEX — THE MONOGRAPH GENERATOR (md -> docx -> pdf)
============================================================================
The user-facing research generator: pick ANY set of bodies — the twelve
registered ones or your own planets (a GM in m^3/s^2, or a mass in kg
and a radius in km) — and the module builds a full personal research
monograph: the model, the exact per-body register tables at working
precision, the tilt registers, the budget closure of THIS set, the
verification certificate of the run that produced it, and the
cross-references into the committed corpus.

    python3 -m planetvortex.cli monograph --bodies "Sun,Earth,Mars" \
            --lang en --format pdf

Formats: md (Markdown), docx (pandoc, the house navy-gold styles),
pdf (LibreOffice headless render of the docx). Everything lands where
--out points (default: results/generated/).

License: LicenseRef-Proprietary-Wild8Highlander-1.0 (see LICENSE.md)
Year: 2026
============================================================================
"""

from __future__ import annotations

import datetime
import json
import math
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from . import classical as cl
from . import klein as kl

MINIROOT = Path(__file__).resolve().parents[2]
PROTOCOL_DIR = MINIROOT / "results" / "protocols"

TEXTS = {
    "en": {
        "title": "The Gravitational Register of {bodies}",
        "subtitle": "A personal monograph of the PLANETVORTEX closed gravifigure",
        "gen_by": "Generated by the planetvortex monograph generator",
        "date": "Date (UTC)",
        "s1": "1. The model in one page",
        "s2": "2. The gravimetric register algebra of the chosen set",
        "s3": "2.1 The exact register dimensions",
        "s4": "2.2 The budget closure of this set",
        "s5": "3. The spatial registers (the inclined sky)",
        "s6": "4. The verification certificate of this run",
        "s7": "5. The corpus and the reproduction commands",
        "t1body": (
            "The Klein quartic $x^3y + y^3z + z^3x = 0$ is the genus-3 surface "
            "whose automorphism group $\\mathrm{{PSL}}(2,7)$ of order 168 "
            "attains the Hurwitz bound $84(g-1)$. Its $\\{{7,3\\}}$ tessellation "
            "carries 24 heptagons — 12 antipodal pairs — and stage V2 of the "
            "bench carries the mass ladder of the chosen bodies in the vertex "
            "angles: $\\alpha_i = 2\\pi/3 - \\sigma\\, s_i$ with "
            "$s_i = \\ln \\mathrm{{GM}}_i - \\langle \\ln \\mathrm{{GM}}\\rangle$. "
            "The geometric-mean normalization makes $\\sum s_i = 0$ exactly, and "
            "that is precisely the condition that the decorated tessellation "
            "closes on the Gauss–Bonnet budget $\\sum \\alpha_i = 8\\pi = "
            "2\\pi(2g-2)$: the Euler characteristic absorbs the mass ladder. "
            "The heavier the body, the wider its heptagon — gravity drawn as "
            "geometry, in exact closed form: $\\cosh R_i = \\cot(\\alpha_i/2)\\,"
            "\\cot(\\pi/7)$, $\\cosh(\\ell_i/2) = \\cos(\\pi/7)/\\sin(\\alpha_i/2)$, "
            "$\\cosh r_i = \\cos(\\alpha_i/2)/\\sin(\\pi/7)$, $A_i = 5\\pi - "
            "7\\alpha_i$."
        ),
        "theorems": "The formal corpus: Theorems A–C, Lemma D, Lemma E (the planar bench), Theorem F (the coset construction), Lemma F (the antipodal freeness), Theorem G (the budget closure), Lemma G (the arc register) — docs/theorems/.",
        "columns": ("body", "GM, m³/s²", "s", "α, rad", "R", "ℓ", "r", "A", "i, °", "λ, rad"),
        "budget_line": (
            "The budget closure of this set: Σα = {alpha} against 8π = {eightpi}"
            " — residual {resid} ({status})."
        ),
        "budget_ok": "the figure closes",
        "budget_bad": "the figure does NOT close (check the normalization)",
        "incl_note": (
            "λ = R̄·i is the arc register of the spatial tilt against the "
            "ecliptic (R̄ = 1 AU); the inclination rows come from the "
            "committed J2000 register (JPL)."
        ),
        "custom_note": (
            "A custom body: GM = {gm:.6e} m³/s²{radius} — registered "
            "locally for this monograph only."
        ),
        "with_radius": ", radius {r} km",
        "cert_intro": (
            "This monograph was generated together with a live verification "
            "run; the checks below were executed by the generator, not quoted."
        ),
        "repro": (
            "Reproduce everything with the committed pipeline (from the "
            "mini-repository root):\n\n"
            "```bash\n"
            "make all-ladders   # P1..P7 + X1..X6 + V1..V2, JSON protocols\n"
            "make test          # the pytest guard\n"
            "make crosslang     # the C99 kernel vs Python\n"
            "make figures600    # this gallery at 600 dpi\n"
            "make monograph     # a sample monograph\n"
            "```\n"
        ),
        "protocol_note": (
            "Every plotted or quoted number of the bench is bound to a JSON "
            "protocol in `results/protocols/` — committed before the run's "
            "tolerance, refreshed after it."
        ),
    },
    "ru": {
        "title": "Гравитационный регистр набора {bodies}",
        "subtitle": "Персональная монография замкнутой гравифигуры PLANETVORTEX",
        "gen_by": "Сгенерировано монограф-генератором planetvortex",
        "date": "Дата (UTC)",
        "s1": "1. Модель на одной странице",
        "s2": "2. Гравиметрическая алгебра регистров выбранного набора",
        "s3": "2.1 Точные размерности регистров",
        "s4": "2.2 Замыкание бюджета этого набора",
        "s5": "3. Пространственные регистры (наклонное небо)",
        "s6": "4. Сертификат верификации этого прогона",
        "s7": "5. Корпус и команды воспроизведения",
        "t1body": (
            "Квартика Клейна $x^3y + y^3z + z^3x = 0$ — поверхность рода 3, "
            "группа автоморфизмов которой $\\mathrm{{PSL}}(2,7)$ порядка 168 "
            "достигает границы Хурвица $84(g-1)$. Её замощение $\\{{7,3\\}}$ "
            "несёт 24 семиугольника — 12 антиподальных пар — и стадия V2 "
            "стенда переносит лестницу масс выбранного набора в углы при "
            "вершинах: $\\alpha_i = 2\\pi/3 - \\sigma\\, s_i$, где "
            "$s_i = \\ln \\mathrm{{GM}}_i - \\langle \\ln \\mathrm{{GM}}\\rangle$. "
            "Нормировка на геометрическое среднее делает $\\sum s_i = 0$ "
            "точно, и это в точности условие замыкания украшенного "
            "разбиения на бюджет Гаусса–Бонне $\\sum \\alpha_i = 8\\pi = "
            "2\\pi(2g-2)$: характеристика Эйлера вбирает лестницу масс. Чем "
            "тяжелее тело, тем шире его семиугольник — гравитация, "
            "начерченная как геометрия, в точных замкнутых формах: "
            "$\\cosh R_i = \\cot(\\alpha_i/2)\\,\\cot(\\pi/7)$, "
            "$\\cosh(\\ell_i/2) = \\cos(\\pi/7)/\\sin(\\alpha_i/2)$, "
            "$\\cosh r_i = \\cos(\\alpha_i/2)/\\sin(\\pi/7)$, $A_i = 5\\pi - "
            "7\\alpha_i$."
        ),
        "theorems": "Формальный корпус: Теоремы A–C, Лемма D, Лемма E (плоский стенд), Теорема F (косет-конструкция), Лемма F (свобода антиподов), Теорема G (замыкание бюджета), Лемма G (дуговой регистр) — docs/theorems/.",
        "columns": ("тело", "GM, м³/с²", "s", "α, рад", "R", "ℓ", "r", "A", "i, °", "λ, рад"),
        "budget_line": (
            "Замыкание бюджета набора: Σα = {alpha} против 8π = {eightpi}"
            " — остаток {resid} ({status})."
        ),
        "budget_ok": "фигура замыкается",
        "budget_bad": "фигура НЕ замыкается (проверьте нормировку)",
        "incl_note": (
            "λ = R̄·i — дуговой регистр пространственного наклона к эклиптике "
            "(R̄ = 1 а.е.); строки наклонений — из зафиксированного "
            "J2000-реестра (JPL)."
        ),
        "custom_note": (
            "Пользовательское тело: GM = {gm:.6e} м³/с²{radius} — "
            "зарегистрировано локально, только для этой монографии."
        ),
        "with_radius": ", радиус {r} км",
        "cert_intro": (
            "Монография сгенерирована вместе с живым прогоном верификации; "
            "проверки ниже выполнены генератором, а не процитированы."
        ),
        "repro": (
            "Воспроизведите всё зафиксированным конвейером (из корня "
            "мини-репозитория):\n\n"
            "```bash\n"
            "make all-ladders   # P1..P7 + X1..X6 + V1..V2, JSON-протоколы\n"
            "make test          # pytest-щит\n"
            "make crosslang     # C99-ядро против Python\n"
            "make figures600    # галерея в 600 dpi\n"
            "make monograph     # образец монографии\n"
            "```\n"
        ),
        "protocol_note": (
            "Каждое число стенда привязано к JSON-протоколу в "
            "`results/protocols/` — допуск фиксируется до прогона, "
            "протокол обновляется после."
        ),
    },
}


def parse_bodies(spec: str) -> Tuple[List[Dict[str, Any]], List[str]]:
    """Parse the --bodies spec: registered names + custom entries of the
    form Name@GM or Name#mass_kg*radius_km."""
    bodies: List[Dict[str, Any]] = []
    notes: List[str] = []
    registered = {b.name: b for b in kl.BODIES}
    for token in [t.strip() for t in spec.split(",") if t.strip()]:
        if "@" in token:
            name, gm_s = token.split("@", 1)
            gm = float(gm_s)
            bodies.append({"body": name, "gm": gm, "kind": "custom", "incl_deg": None})
            notes.append(TEXTS["en"]["custom_note"].format(gm=gm, radius=""))
        elif "#" in token:
            head = token.split("#", 1)
            name = head[0]
            parts = head[1].split("*")
            mass_kg = float(parts[0])
            radius_km = float(parts[1]) if len(parts) > 1 else None
            gm = mass_kg * cl.G_NEWTON
            note = TEXTS["en"]["custom_note"].format(gm=gm, radius="")
            if radius_km:
                note += TEXTS["en"]["with_radius"].format(r=radius_km)
            bodies.append({"body": name, "gm": gm, "kind": "custom", "incl_deg": None})
            notes.append(note)
        elif token in registered:
            b = registered[token]
            try:
                reg = cl.spatial_register_by_name(token)
                incl = reg.inclination_deg
            except KeyError:
                incl = None
            bodies.append({"body": token, "gm": b.gm, "kind": b.kind, "incl_deg": incl})
        else:
            raise SystemExit(
                f"unknown body {token!r} — use one of {sorted(registered)} "
                "or Name@GM or Name#mass_kg*radius_km"
            )
    if len(bodies) < 2:
        raise SystemExit("at least two bodies are needed for the normalization")
    return bodies, notes


def register_rows(bodies: List[Dict[str, Any]]) -> Tuple[List[Dict[str, Any]], Dict[str, float]]:
    """The register algebra of an arbitrary set (the V2 formulas)."""
    ln_gm = [math.log(b["gm"]) for b in bodies]
    mean = sum(ln_gm) / len(ln_gm)
    s = [v - mean for v in ln_gm]
    worst_neg = max(-x for x in s)
    sigma = (1.0 - 0.05) * (kl.EUCLIDEAN_CEILING - kl.REGULAR_ANGLE) / worst_neg
    rows = []
    for b, s_i in zip(bodies, s):
        alpha = kl.REGULAR_ANGLE - sigma * s_i
        big_r, edge, inr, area = kl.register_dims(alpha)
        rows.append(
            {
                "body": b["body"],
                "gm": b["gm"],
                "s": s_i,
                "alpha": alpha,
                "R": big_r,
                "edge": edge,
                "inradius": inr,
                "area": area,
                "incl_deg": b["incl_deg"],
                "arc": None if b["incl_deg"] is None else math.radians(b["incl_deg"]),
            }
        )
    alpha_sum = sum(r["alpha"] for r in rows)
    return rows, {"sigma": sigma, "alpha_sum": alpha_sum}


def verification_certificate() -> List[Tuple[str, bool, str]]:
    """The live mini-battery executed by the generator itself."""
    import numpy as np

    from . import spatial as sp

    checks: List[Tuple[str, bool, str]] = []
    exact = kl.register_algebra_exact(dps=30)
    checks.append(
        ("Σα = 8π (mpmath, 30 dps)", bool(exact["budget_ok"]), str(exact["alpha_sum_residual"]))
    )
    alg = kl.register_algebra_float()
    checks.append(
        ("Σα = 8π (float64)", alg["alpha_sum_residual"] <= 1e-9, f"{alg['alpha_sum_residual']:.2e}")
    )
    checks.append(
        (
            "the hyperbolic Pythagoras (12 cells)",
            alg["worst_pythagoras_residual"] <= 1e-12,
            f"{alg['worst_pythagoras_residual']:.2e}",
        )
    )
    tilt = sp.tilt_matrix(7.00497902, 48.33076593)
    orth = float(np.max(np.abs(tilt.T @ tilt - np.eye(3))))
    checks.append(("the SO(3) tilt orthogonality", orth <= 1e-14, f"{orth:.2e}"))
    for name in ("P4_fano_algebra", "X4_hyperbolic_figure", "V2_klein_tiling"):
        path = PROTOCOL_DIR / f"{name}_default.json"
        if path.exists():
            with path.open("r", encoding="utf-8") as fh:
                proto = json.load(fh)
            checks.append((f"protocol {name}", bool(proto["check"]["passed"]), "committed"))
    return checks


def build_markdown(bodies_spec: str, lang: str = "en") -> Tuple[str, Path, Path]:
    """Build the monograph markdown; return (text, md_path, stem)."""
    T = TEXTS[lang]
    bodies, notes = parse_bodies(bodies_spec)
    rows, stats = register_rows(bodies)
    body_names = ", ".join(b["body"] for b in bodies)
    stem = (
        "planetvortex-monograph-"
        + "-".join("".join(ch for ch in b["body"].lower() if ch.isalnum()) for b in bodies)
    )[:80] + f"-{lang}"

    lines: List[str] = []
    lines.append(f"---")
    lines.append(f'title: "{T["title"].format(bodies=body_names)}"')
    lines.append(f'subtitle: "{T["subtitle"]}"')
    lines.append(
        f"date: {datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}"
    )
    lines.append("---")
    lines.append("")
    lines.append(f"## {T['s1']}")
    lines.append("")
    lines.append(T["t1body"].format())
    lines.append("")
    lines.append(f"## {T['s2']}")
    lines.append("")
    lines.append(f"### {T['s3']}")
    lines.append("")
    cols = T["columns"]
    lines.append("| " + " | ".join(cols) + " |")
    lines.append("|" + "---|" * len(cols))
    for r in rows:
        incl = "—" if r["incl_deg"] is None else f"{r['incl_deg']:.4f}"
        arc = "—" if r["arc"] is None else f"{r['arc']:.6f}"
        lines.append(
            f"| **{r['body']}** | {r['gm']:.6e} | {r['s']:+.4f} | {r['alpha']:.6f} | "
            f"{r['R']:.6f} | {r['edge']:.6f} | {r['inradius']:.6f} | {r['area']:.6f} | "
            f"{incl} | {arc} |"
        )
    lines.append("")
    if notes:
        for n in notes:
            lines.append(f"- {n}")
        lines.append("")
    lines.append(T["incl_note"])
    lines.append("")
    lines.append(f"### {T['s4']}")
    lines.append("")
    resid = abs(stats["alpha_sum"] - 8 * math.pi)
    status = T["budget_ok"] if resid <= 1e-9 else T["budget_bad"]
    lines.append(
        T["budget_line"].format(
            alpha=f"{stats['alpha_sum']:.12f}",
            eightpi=f"{8 * math.pi:.12f}",
            resid=f"{resid:.2e}",
            status=("**" + status + "**"),
        )
    )
    lines.append("")
    lines.append(f"## {T['s5']}")
    lines.append("")
    lines.append(
        "The spatial registers of the bench: the tilt operators "
        "$T = R_z(\\Omega) R_x(i) \\in SO(3)$, the arc registers "
        "$\\lambda_i = \\bar{R}\\, i_i$ and the mutual-inclination matrix are "
        "certified by stage V1 (protocol `V1_inclined_registers.json`); the "
        "3D Newtonian run from the real J2000 sky carries the conservation "
        "of the energy and of the full angular-momentum vector."
    )
    lines.append("")
    lines.append(f"## {T['s6']}")
    lines.append("")
    lines.append(T["cert_intro"])
    lines.append("")
    lines.append("| # | check | result | recorded |")
    lines.append("|---|-------|:------:|----------|")
    for k, (name, ok, recorded) in enumerate(verification_certificate(), start=1):
        lines.append(f"| {k} | {name} | {'**PASS**' if ok else '**FAIL**'} | {recorded} |")
    lines.append("")
    lines.append(f"## {T['s7']}")
    lines.append("")
    lines.append(T["theorems"])
    lines.append("")
    lines.append(T["protocol_note"])
    lines.append("")
    lines.append(T["repro"])
    lines.append("")

    text = "\n".join(lines)
    out_dir = MINIROOT / "results" / "generated"
    out_dir.mkdir(parents=True, exist_ok=True)
    md_path = out_dir / f"{stem}.md"
    md_path.write_text(text, encoding="utf-8")
    return text, md_path, Path(stem)


def render_docx(md_path: Path) -> Path:
    """Pandoc -> DOCX with the house reference styles (graceful fallback)."""
    docx_path = md_path.with_suffix(".docx")
    reference = MINIROOT.parent / "polyvortex" / "docs" / "monograph" / "monograph_RU.docx"
    cmd = ["pandoc", str(md_path), "-o", str(docx_path), "--toc", "--toc-depth=2"]
    if reference.exists():
        cmd += ["--reference-doc", str(reference)]
    subprocess.run(cmd, check=True)
    return docx_path


def render_pdf(docx_path: Path) -> Path:
    """LibreOffice headless: DOCX -> PDF."""
    pdf_path = docx_path.with_suffix(".pdf")
    subprocess.run(
        [
            "libreoffice",
            "--headless",
            "--convert-to",
            "pdf",
            "--outdir",
            str(docx_path.parent),
            str(docx_path),
        ],
        check=True,
        timeout=600,
        capture_output=True,
    )
    return pdf_path


def generate(
    bodies_spec: str, lang: str = "en", fmt: str = "all", out_dir: Path | None = None
) -> Dict[str, Path]:
    """The full pipeline: md -> docx -> pdf. Returns the artifact paths."""
    if lang not in TEXTS:
        raise SystemExit(f"lang must be one of {sorted(TEXTS)}")
    _text, md_path, stem = build_markdown(bodies_spec, lang)
    if out_dir is not None:
        target = Path(out_dir)
        target.mkdir(parents=True, exist_ok=True)
        md_path = target / md_path.name
        md_path.write_text(_text, encoding="utf-8")
    artifacts: Dict[str, Path] = {"md": md_path}
    fmts = {"md", "docx", "pdf"} if fmt == "all" else {fmt}
    if "docx" in fmts or "pdf" in fmts:
        try:
            docx = render_docx(md_path)
            artifacts["docx"] = docx
        except (FileNotFoundError, subprocess.CalledProcessError) as exc:
            print(f"  ! docx render skipped: {exc}")
    if "pdf" in fmts and "docx" in artifacts:
        try:
            artifacts["pdf"] = render_pdf(artifacts["docx"])
        except (FileNotFoundError, subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
            print(f"  ! pdf render skipped: {exc}")
    return artifacts
